numpy arrays are nothing but it is an numberical python and these are similar to lists and tuplles
advantages over lists:
1. allows several mathematical opeartaions
2. faster opearations

In [14]:
#importing numpy
import numpy as np

In [5]:
#import the process time
from time import process_time

lets check the prcessing time(time taken to run) for lists and numpy
LIST VS NUMPY

In [6]:
#lists
list = [i for i in range(10,000)]
start_time = process_time()
list = [i + 5 for i in list]#here i am taking all values from the list and adding 5 to the each value
end_time = process_time()
print(end_time - start_time)#for calculating process time

0.00011727999999999739


In [7]:
#numpy array
import numpy as np
np_array = np.array([i for i in range(10,000)])
start_time = process_time()
np_array = np_array + 5#here i am adding 5 to the each value.... we can also write np_array += 5
end_time = process_time()
print(end_time - start_time)#for calculating process time

0.00013985100000013517


here we observed that processing speed is fast in numpy array compared to lists

creating numpy array

In [8]:
#create lists
list = [1,2,3,4]
print(list)
type(list)

[1, 2, 3, 4]


list

In [9]:
#creating numpy array
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

here nd denotes n dimesions and as we observe in lists the values are seperated using commas where as in array there are no commas

creating onde dimesnisonal array

In [10]:
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

here 4 denotes no of rows

creating 2D array

In [17]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
a.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

here 2 denotes rows and 4 denotes columns

converting the element of array from int to float

In [18]:
a = np.array([[1,2,3,4],[5,6,7,8]],dtype = float)
print(a)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholders in numpy arrays:which means all values in array are same like all zeroes or ones or any number

In [20]:
#numpy array of zeroes
a = np.zeros((4,5))
print(a)
#here 4,5 reperesnts shaape which means how many rows and cols should my array consist

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#numpy array of ones
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#numpy array of particluar value
a = np.full((3,2),7)
print(a)
#here 7 indicates the number with which i want to create an array

[[7 7]
 [7 7]
 [7 7]]


In [23]:
#creating an identity matrix
#here we no need to mention any rows or columns as identity matrix has same rows and columns
a = np.eye(4)
print(a)
#here 4 rep both rows and cols



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#creating a numpy with random values
a = np.random.random((3,4))
print(a)
#here all values are in the range of 0 and 1 and this values change everytm we run

[[0.85948369 0.79147495 0.91386011 0.13292422]
 [0.10893103 0.41193039 0.85024294 0.60345819]
 [0.59799166 0.37202589 0.11091922 0.76430226]]


In [28]:
#creating random integer values within specific range
a = np.random.randint(10,100,(3,4))
print(a)
#here 10,100 indicates the range and 3,4 indicates shape

[[87 59 14 98]
 [80 83 16 70]
 [47 70 82 57]]


In [32]:
#creating an array of evenly spaced value
a = np.linspace(10,30,5)
print(a)
#here 10and 30 indicates range where as 5 indicates the number of numbers should be print
b = np.linspace(10,20,4)
print(b)

[10. 15. 20. 25. 30.]
[10.         13.33333333 16.66666667 20.        ]


In [33]:
#creating an array of evenly space specifing step
a = np.arange(10,30,5)
print(a)
#here 5 indicates that the number should be skipped five times

[10 15 20 25]


In [34]:
#converting an list to numpy
list = [1,2,3,4]
np_array = np.asarray(list)
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

analysing(getting all information) numpy array

In [38]:
a = np.random.randint(10,90,(5,5))
print(a)
#array dimension
print(a.shape)
#no of dimensions
print(a.ndim)
#no of elements in an array
print(a.size)
#checking data types of elements of array
print(a.dtype)

[[61 67 83 62 22]
 [48 40 71 67 50]
 [80 27 44 86 18]
 [58 63 39 89 53]
 [26 19 58 38 70]]
(5, 5)
2
25
int64


mathematical opeartions of np array

In [39]:
#list
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [41]:
#for np array
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a + b)#or print(np.add(a , b))
print(a - b)
print(a * b)
print(a / b)

[[9 8 2]
 [1 9 6]
 [9 1 7]]
[[17 18 19]
 [16 12 13]
 [11 15 13]]
[[26 26 21]
 [17 21 19]
 [20 16 20]]
[[ -8 -10 -17]
 [-15  -3  -7]
 [ -2 -14  -6]]
[[153 144  38]
 [ 16 108  78]
 [ 99  15  91]]
[[0.52941176 0.44444444 0.10526316]
 [0.0625     0.75       0.46153846]
 [0.81818182 0.06666667 0.53846154]]


In [45]:
#transpose
a = np.random.randint(10,20,(2,3))
print(a)
trans = np.transpose(a)#trans = a. T
print(trans)

[[13 10 19]
 [10 11 12]]
[[13 10]
 [10 11]
 [19 12]]


In [48]:
#reshapping array
a = np.random.randint(10,20,(2,3))
print(a)
print(a.shape)


[[14 18 13]
 [13 17 10]]
(2, 3)


In [49]:
b = a.reshape(3,2)
print(b)
print(b.reshape)


[[14 18]
 [13 13]
 [17 10]]
<built-in method reshape of numpy.ndarray object at 0x79ca97918a50>
